<?php

$labels = array();

$labels['hmsfromrc'] = "HMS from RC";
$labels['autoreply'] = "AutoResponder";
$labels['forwarder'] = "Forward E-Mail";

$labels['ar_enabled'] = "Enabled";
$labels['ar_subject'] = "AutoResponder Message Subject";
$labels['ar_body'] = "AutoResponder Message Body";
$labels['ar_ae_enabled'] = "Disable AutoResponder After";
$labels['ar_ae_warning'] = "You selected a date which earlier than tomorrow. Please recheck.";

$labels['fw_enabled'] = $labels['ar_enabled'];

?>