<?php

$labels = array();

$labels['hmsfromrc'] = "HMS from RC";
$labels['autoreply'] = "Automatyczne odpowiedzi";
$labels['forwarder'] = "Forward E-Mail";

$labels['ar_enabled'] = "Włączone";
$labels['ar_subject'] = "Temat odpowiedzi";
$labels['ar_body'] = "Treść odpowiedzi";
$labels['ar_ae_enabled'] = "Wyłącz odpowiedzi po";
$labels['ar_ae_warning'] = "Wprowadź ponownie - nie wcześniej niż jutro.";

$labels['fw_enabled'] = $labels['ar_enabled'];
$labels['fw_address'] = "Przesyłaj do";
$labels['fw_keeporiginal'] = "Zachowaj oryginalną wiadomość";
$labels['ar_fw_invalidaddress'] = "Nieprawidłowy adres, popraw.";

?>
