<?php

$labels = array();

$labels['hmsfromrc'] = "HMS from RC";
$labels['autoreply'] = "Otomatik Yanıt";
$labels['forwarder'] = "Yönlendirme";

$labels['ar_enabled'] = "Aktif";
$labels['ar_subject'] = "Otomatik Yanıt Mesaj Konusu";
$labels['ar_body'] = "Otomatik Yanıt Mesajı";
$labels['ar_ae_enabled'] = "Şu tarihten sonra otomatik yanıtı kapat";
$labels['ar_ae_warning'] = 'Otomatik yanıt kapatma tarihi olarak yarından daha erken bir tarih seçtiniz. Özellik devre dışı bırakıldı.';

$labels['fw_enabled'] = $labels['ar_enabled'];

?>